/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/w77UGQIm3Uf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function calender() {
  return (
    <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg">
      <div className="flex items-center justify-between px-4 py-3 border-b dark:border-gray-800">
        <div className="text-lg font-medium text-gray-900 dark:text-gray-100">May 2024</div>
        <div className="flex items-center space-x-2">
          <button className="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-gray-950 dark:focus-visible:ring-gray-300">
            <ChevronLeftIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          </button>
          <button className="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-gray-950 dark:focus-visible:ring-gray-300">
            <ChevronRightIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          </button>
        </div>
      </div>
      <div className="grid grid-cols-7 gap-2 p-4">
        <div className="flex items-center justify-center text-sm font-medium text-gray-500 dark:text-gray-400">Sun</div>
        <div className="flex items-center justify-center text-sm font-medium text-gray-500 dark:text-gray-400">Mon</div>
        <div className="flex items-center justify-center text-sm font-medium text-gray-500 dark:text-gray-400">Tue</div>
        <div className="flex items-center justify-center text-sm font-medium text-gray-500 dark:text-gray-400">Wed</div>
        <div className="flex items-center justify-center text-sm font-medium text-gray-500 dark:text-gray-400">Thu</div>
        <div className="flex items-center justify-center text-sm font-medium text-gray-500 dark:text-gray-400">Fri</div>
        <div className="flex items-center justify-center text-sm font-medium text-gray-500 dark:text-gray-400">Sat</div>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
